mod commands;

use tracel_xtask::prelude::*;

#[macros::base_commands]
pub enum Command {
    /// Build the app in release mode with every action, then run it.
    Run(commands::run::RunCmdArgs),
    /// Generate compact runtime media plus every application and tray icon.
    Assets(commands::assets::AssetsCmdArgs),
    /// Alias for `assets`, retained for compatibility.
    Icons(commands::icons::IconsCmdArgs),
}

fn main() -> anyhow::Result<()> {
    let (args, environment) = init_xtask::<Command>(parse_args::<Command>()?)?;
    match args.command {
        Command::Run(cmd_args) => commands::run::handle_command(cmd_args),
        Command::Assets(cmd_args) => commands::assets::handle_command(cmd_args),
        Command::Icons(cmd_args) => commands::icons::handle_command(cmd_args),
        // `dispatch_base_commands` is generated by the `base_commands` macro.
        _ => dispatch_base_commands(args, environment),
    }?;
    Ok(())
}
